client/urls.py
from django.urls import path

from client import views

app_name = "client"
urlpatterns = [
    path("", views.index_view, name="index")
    # re_path(r"^(?P<city>\w+)/(?P<country>\w+)/", views.index_view, name="index"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path("", include("server.urls")),  # 'api/'
    path("", include("users.urls")),
    path("", include("client.urls")),
]

if not settings.TESTING:
    try:
        from debug_toolbar.toolbar import debug_toolbar_urls

        urlpatterns = [
            *urlpatterns,
        ] + debug_toolbar_urls()
    except ImportError:
        pass

server/urls.py
import os
from django.conf import settings
from dotenv import load_dotenv

from django.urls import path

from server import views

load_dotenv()

app_name = "server"

urlpatterns = [
    path("api/" if settings.DEBUG else f"{os.getenv("API_URL")}/", views.api.urls),
    path("search/<str:query>/", views.city_search_view, name="city_search"),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"
urlpatterns = [
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout/", views.logout_view, name="logout"),
]

client/models.py
from django.db import models

# Create your models here.

server/models.py
from django.db import models


class City(models.Model):
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=60)
    lat = models.FloatField()
    lon = models.FloatField()
    population = models.IntegerField()

    class Meta:
        db_table = "weather_cities"
        verbose_name_plural = "cities"

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

client/views.py
from loguru import logger as base_logger
from server.views import weather_view

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

logger = base_logger.bind(name="client.views")


# path('', views.index_view, name="index")
@login_required
async def index_view(request):
    logger.info("Index view")
    request_get = request.GET.get
    data = await weather_view(
        request,
        city=request_get("city", "Tokyo"),
        country=request_get("country", "Japan"),
    )

    template_name = "components/weather.html" if request.htmx else "index.html"

    response = render(request, template_name, {"data": data})
    return response

server/views.py
from typing import List, Optional
from django.http import JsonResponse
from ninja import NinjaAPI, Query
from ninja.schema import BaseModel
from channels.db import database_sync_to_async

# from datetime import time

from server.models import City
from server.openmeteo import WeatherAPI, CurrentWeather, HourlyWeather, DailyWeather

api = NinjaAPI(urls_namespace="api")


class CitySchema(BaseModel):
    city: str
    lat: float
    lon: float
    country: str
    population: int


@database_sync_to_async
def get_cities(q):
    queryset = City.objects.filter(city__icontains=q)[:4]
    return list(queryset.values("city", "lat", "lon", "country", "population"))


@api.get("/cities", response=List[CitySchema], url_name="city")
async def cities_view(request, q: Optional[str] = Query(None)):
    return await get_cities(q)


async def city_search_view(request, query):
    return JsonResponse(await cities_view(request, query), safe=False)


# class CurrentWeather(BaseModel):
#     temperature: float
#     apparent_temperature: float
#     # is_day: int
#     icon_url: str
#     # precipitation: float
#     rain: float
#     # weather_code: int
#     wind_speed: float
#     # wind_direction: float
#
#
# class HourlyWeather(BaseModel):
#     date: List[time]
#     icon_url: List[str]
#     description: List[str]
#     # is_day: List[bool]
#     temperature: List[float]
#     humidity: List[int]
#     # weather_code: List[int]
#
#
# class DailyWeather(BaseModel):
#     time: List[str]
#     days_of_week: List[str]
#     icon_url: List[str]
#     description: List[str]
#     # weather_code: List[int]
#     temperature_max: List[float]
#     temperature_min: List[float]
#     # sunrise: List[str]
#     # sunset: List[str]
#     uv_index: List[int]


class WeatherSchema(BaseModel):
    city: str
    country: str
    latitude: float
    longitude: float
    current: CurrentWeather
    hourly: List[HourlyWeather]
    daily: List[DailyWeather]


@api.get("/weather", response=WeatherSchema, url_name="weather")
async def weather_view(request, city: str, country: Optional[str] = Query(None)):
    try:
        weather = WeatherAPI(city=city, country=country)
        data = await weather.data()
        return data
    except Exception as e:
        raise e

users/views.py
from asgiref.sync import sync_to_async
from django.contrib.auth import alogin, alogout
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.forms import AuthenticationForm


# path("/accounts/login", views.login_view, name="login")
async def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if await sync_to_async(form.is_valid)():
            user = await sync_to_async(form.get_user)()
            await alogin(request, user)
            return redirect(reverse("client:index"))

    else:
        form = await sync_to_async(AuthenticationForm)()

        template_name = "components/auth.html" if request.htmx else "index.html"

        return render(request, template_name, {"form": form})


# path("/accounts/logout", views.logout_view, name="logout")
async def logout_view(request):
    await alogout(request)
    return redirect(reverse("client:index"))

templates/components/air_conditions.html
{% load client_filters %}
<div class="w-full">
    <div class="flex flex-col px-7 py-6 bg-light-gray rounded-3xl">
        <h1 class="text-[13px] leading-[18px] text-dark-white font-semibold mb-4">AIR CONDITIONS</h1>
        <div class="w-full grid grid-rows-2 grid-cols-2 gap-3">
            <div class="flex">
                <iconify-icon icon="mdi:thermometer" class="text-dark-white text-2xl mr-3"></iconify-icon>
                <div class="flex flex-col">
                    <span class="text-dark-white text-lg font-light mb-2">Real Feel</span>
                    <span class="text-light-white text-2xl font-semibold">{{ data.current.apparent_temperature }}°</span>
                </div>
            </div>
            <div class="flex ml-4">
                <iconify-icon icon="fa-solid:wind" class="text-dark-white text-2xl mr-3"></iconify-icon>
                <div class="flex flex-col">
                    <span class="text-dark-white text-lg font-light mb-2">Wind</span>
                    <span class="text-light-white text-2xl font-semibold">{{ data.current.wind_speed }} km/h</span>
                </div>
            </div>
            <div class="flex">
                <iconify-icon icon="ion:water" class="text-dark-white text-2xl mr-3"></iconify-icon>
                <div class="flex flex-col">
                    <span class="text-dark-white text-lg font-light mb-2">Chance of rain</span>
                    <span class="text-light-white text-2xl font-semibold">{{ data.current.rain }}%</span>
                </div>
            </div>
            <div class="flex ml-4">
                <iconify-icon icon="fa-solid:sun" class="text-dark-white text-2xl mr-3"></iconify-icon>
                <div class="flex flex-col">
                    <span class="text-dark-white text-lg font-light mb-2">UV index</span>
                    <span x-data="{ uv_index: {{ data.daily.uv_index|to_json }} }"
                          x-text="uv_index[0] + '%'"
                          class="text-light-white text-2xl font-semibold"></span>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/auth.html
<div
  id="auth"
  class="flex flex-col w-full mx-[22px] items-center justify-center"
>
  <c-auth.login />
</div>

templates/components/base.html
<main id="root" class="flex bg-dark-gray w-[1317px] h-[792px]">
    <div class="flex flex-grow relative my-9 mx-[30px]">
        <c-sidebar.main />
        <div id="content" class="flex w-full">
            {% if request.resolver_match.view_name == "users:login" %}
                <c-auth />
            {% else %}
                <c-weather />
            {% endif %}
        </div>
    </div>
</main>

templates/components/city_info.html
{% load static %}
<div class="w-full">
    <div class="flex px-11 py-7">
        <div class="flex-grow">
            <div class="mb-6">
                <h2 class="text-4xl text-light-white font-semibold mb-1.5">{{ data.city }}</h2>
                <h3 class="text-xl text-light-white font-semibold">{{ data.country }}</h3>
                <span class="text-sm text-dark-white font-normal tracking-wide">Chance of rain: {{ data.current.rain }}%</span>
            </div>
            <div class="mb-2">
                <span class="text-6xl text-light-white font-medium">{{ data.current.temperature }}°</span>
            </div>
        </div>
        <img class="h-[194px]"
             src="{% static data.current.icon_url %}"
             alt="{{ data.current.description }}" />
    </div>
</div>

templates/components/forecast/daily.html
{# TODO: make full REST API on server side (without js) #}
{% load static client_filters %}
<div class="flex flex-col w-full p-9 bg-light-gray rounded-3xl"
    {#x-data="{ daily: {{ data.daily|to_json }} }"#}
    >
    <h1 class="text-[13px] leading-[18px] text-dark-white font-semibold mb-5">7-DAY FORECAST</h1>
    <div class="h-full grid grid-rows-7 gap-auto">
        {% for time in data.daily.time %}
            <div class="w-full">
                {% if not forloop.first %}<div class="flex bg-gray-600 w-full h-[.5px]"></div>{% endif %}
                <div class="grid grid-cols-3 items-center w-full">
                    <span class="text-base text-dark-white font-light">
                        {% if forloop.first %}
                            Today
                        {% else %}
                            {{ data.daily.days_of_week|index:forloop.counter0 }}
                        {% endif %}
                    </span>
                    <div class="px-3">
                        <img src="{% static data.daily.icon_url|index:forloop.counter0 %}"
                             alt="{{ data.daily.description|index:forloop.counter0 }}" />
                    </div>
                    <div class="text-right text-base text-dark-white">
                        <span class="text-light-white font-semibold">{{ data.daily.temperature_max|index:forloop.counter0 }}°</span>/
                        <span class="text-dark-white font-light">{{ data.daily.temperature_min|index:forloop.counter0 }}°</span>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/components/forecast/hourly.html
{% load static client_filters %}
<div class="flex w-full">
    <div class="flex flex-col w-full px-7 py-6 bg-light-gray rounded-3xl">
        <h1 class="text-[13px] leading-[18px] text-dark-white font-semibold mb-4">TODAY'S FORECAST</h1>
        <div class="w-full grid grid-cols-6">
            {% for time in data.hourly.date %}
                <div class="flex">
                    {% if not forloop.first %}<div class="flex bg-slate-600 h-full w-[0.5px]"></div>{% endif %}
                    <div class="flex flex-col items-center">
                        <span class="text-sm text-dark-white font-semibold">{{ data.hourly.date|index:forloop.counter0 }}</span>
                        <span class="px-8">
                            <img src="{% static data.hourly.icon_url|index:forloop.counter0 %}"
                                 alt="{{ data.hourly.description|index:forloop.counter0 }}" />
                        </span>
                        <span class="text-2xl text-light-white">{{ data.hourly.temperature|index:forloop.counter0 }}°</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/components/search.html
<div x-data="citySearch()" class="relative">
    <input type="text"
           x-model="query"
           @input.debounce.150ms="fetchCities()"
           @keyup.arrow-down="highlightNext()"
           @keyup.arrow-up="highlightPrevious()"
           @keyup.enter.prevent="selectCity()"
           placeholder="Search for cities"
           class="w-full min-w-[46rem] py-[13px] px-2 rounded-[.6rem] bg-light-gray text-[13px] leading-[18px] text-light-white text-light-text outline-none placeholder:text-light-white" />
    <div x-show="cities.length > 0"
         class="absolute left-0 right-0 overflow-y-auto text-[13px] leading-[18px] mt-2 text-light-white bg-light-gray gap-2 rounded-[.6rem]">
        <template x-for="(city, index) in cities" :key="index">
            <div :class="'flex flex-col p-2 rounded-[.6rem] cursor-pointer ' + (index === highlightedIndex ? 'bg-dark-white' : '')"
                 @click="selectCity(index)">
                <span x-text="city.city"></span>
                <span x-text="city.country"></span>
            </div>
        </template>
    </div>
</div>

templates/components/sidebar/button.html
<button
    {{
    attrs
    }}
    type="button"
    x-data="{
    activebtn: window.location.pathname === '{{ url }}' ? 'font-bold' : 'font-normal',
    updateActive() {
    this.activebtn = (window.location.pathname === '{{ url }}');
    }
    }"
    x-init="() => {
    window.addEventListener('htmx:afterSwap', () => this.updateActive());
    this.$watch('activebtn', () => {});  // Force reactivity
    }"
    :class="'flex flex-col items-center mt-8 text-light-white cursor-pointer ' + activebtn"
    hx-get="{{ url }}"
    hx-target="#content"
    hx-swap="innerHTML"
    hx-trigger="click"
    hx-push-url="true"
    >
    <iconify-icon icon="{{ icon }}" class="text-xl mb-3"></iconify-icon>
    <span class="text-sm">{{ text }}</span>
</button>

templates/components/sidebar/main.html
{% load static %}
<div class="py-6 px-[15px] flex flex-col items-center rounded-3xl bg-light-gray">
    <img src="{% static 'assets/icons/logo.png' %}"
         alt=""
         class="w-11 mb-[1.25rem]" />
    <c-sidebar.button icon="fa-solid:cloud-sun-rain" text="Weather" url='{% url 'client:index' %}' />
    <c-sidebar.button icon="dashicons:menu-alt" text="Cities" url="/cities" />
    {% if not request.user.is_authenticated %}
        <c-sidebar.button icon="tdesign:user-filled" text="Auth" url="{% url 'users:login' %}" />
    {% endif %}
    <c-sidebar.button icon="material-symbols:logout" text="Logout" url="{% url 'users:logout' %}" />
</div>

templates/components/weather.html
<div id="weather" class="flex w-full">
  <div class="flex flex-col w-full mx-[22px]">
    <c-search />
    <div class="flex min-w-[46rem]">
      <c-city-info />
    </div>
    <div class="flex flex-grow min-w-[46rem] mb-4">
      <c-forecast.hourly />
    </div>
    <div class="flex min-w-[46rem]">
      <c-air-conditions />
    </div>
  </div>
  <div class="flex w-full mt-[68px]">
    <c-forecast.daily />
  </div>
</div>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en-US">
    <head>
        <title>Weather App</title>
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'favicon.ico' %}" />
        <script defer src="{% static 'vendored/alpinejs-3.x.x.min.js' %}"></script>
        <script src="{% static "vendored/htmx/2.0.4.min.js" %}"></script>
        <script src="{% static "vendored/htmx/preload@2.1.0.min.js" %}"></script>
        <script src="{% static "vendored/iconify-icon-2.2.0.min.js" %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body hx-ext="preload" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <c-base />
        <script src="{% static "js/search.js" %}"></script>
        <script>
              document.addEventListener("DOMContentLoaded", function () {
                // Handle browser back/forward navigation
                window.addEventListener("popstate", function (event) {
                  // Reload main content from current URL
                  htmx.ajax("GET", window.location.href, {
                    target: "#content",
                    swap: "innerHTML",
                    headers: {
                      "HX-Request": "true", // Force partial responses
                    },
                  });
                });
              });
        </script>
    </body>
</html>